spring.application.name=TestingWithAuth
server.port=8090
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5432/Auth
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=bipin
spring.security.user.password=bipin